##########
# collectionbuilder-sa
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-sa
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://www.lib.uidaho.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /digital/dukesilver
# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/collectionbuilder-sa-spec-exhibits
# shared assets
digital-assets: https://www.lib.uidaho.edu/assets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Duke Silver Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Celebrating the influential 21st century jazz musician
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Duke Silver was perhaps the most influential jazz musician at the turn of the millenium. This collection encompasses his papers, correspondance and personal effects." 
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: April Fools
# Organization branding
organization-name: "Special Collections and Archives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/special-collections/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

##########
# COLLECTION SETTINGS
#
# provide location of the digital objects folder,
# If using local folder, dir name with proceeding slash. If using external web location, provide full URL
objects: https://webpages.uidaho.edu/library/spec/objects/dukesilver
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: dukesilver
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'dukesilver'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
