##########
# collectionbuilder-sa
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-sa
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://www.lib.uidaho.edu
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /digital/dodson
# location of code, the full url to your github repository
source-code: https://github.com/uidaholib/collectionbuilder-sa-spec-exhibits
# shared assets
digital-assets: https://www.lib.uidaho.edu/assets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Richard W. Dodson Collection of Science Fiction
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Correspondence between Richard W. Dodson, Edward E. ("Doc") Smith, and other science fiction authors of the 20th century
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "A collection of Richard W. Dodson's (1915-2008) letters and ephemera to and from Edward Elmer 'Doc' Smith (1890-1965), chemist and pioneer science fiction writer, and other science fiction authors, editors, and friends, including Clark Ashton Smith and Abraham Merritt. Dodson began writing to Smith as a high school student, exchanging letters that ranged from the nature of science fiction writing and critiques of Smith's work to the study of science. Their correspondence spanned almost decades, during which time Dodson grew up to become a prominent atomic scientist."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: owikle
# Organization branding
organization-name: "Digital Initiatives, University of Idaho Library"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://www.lib.uidaho.edu/media/digital/justdi_logo_sm.png
organization-logo-nav: https://www.lib.uidaho.edu/media/digital/bannerlogo_allwhite.png

##########
# COLLECTION SETTINGS
#
# provide location of the digital objects folder,
# If using local folder, dir name with proceeding slash. If using external web location, provide full URL
objects: https://www.lib.uidaho.edu/digital/objects/dodson
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: dodson
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'dodson'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
